# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-08 15:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='dropshipp',
            field=models.CharField(choices=[('\u0422\u043e\u043b\u044c\u043a\u043e \u0434\u0440\u043e\u043f\u0448\u0438\u043f\u043f\u0438\u043d\u0433', '\u0422\u043e\u043b\u044c\u043a\u043e \u0434\u0440\u043e\u043f\u0448\u0438\u043f\u043f\u0438\u043d\u0433'), ('\u0418\u043d\u043e\u0433\u0434\u0430 \u043f\u043b\u0430\u043d\u0438\u0440\u0443\u044e', '\u0418\u043d\u043e\u0433\u0434\u0430 \u043f\u043b\u0430\u043d\u0438\u0440\u0443\u044e'), ('\u041d\u0435\u0442', '\u041d\u0435\u0442')], default='\u041d\u0435\u0442', max_length=32, verbose_name='\u0421\u0438\u0441\u0442\u0435\u043c\u0430 \u0434\u0440\u043e\u043f\u0448\u0438\u043f\u043f\u0438\u043d\u0433'),
        ),
        migrations.AddField(
            model_name='user',
            name='information',
            field=models.TextField(blank=True, null=True, verbose_name='\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f \u043e \u0434\u0435\u044f\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u0438'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=19173961, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='\u041d\u043e\u043c\u0435\u0440 \u043c\u043e\u0436\u0435\u0442 \u0431\u044b\u0442\u044c \u0432\u0432\u0435\u0434\u0451\u043d \u0432 \u043e\u0434\u043d\u043e\u043c \u0438\u0437 \u0444\u043e\u0440\u043c\u0430\u0442\u043e\u0432: +380111111111, 380111111111, 80111111111, 0111111111', regex='^\\+{0,1}\\d{9,15}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u0421\u0430\u0439\u0442'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='\u042d\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u0430\u044f \u043f\u043e\u0447\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='\u0418\u043c\u044f'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='\u0410\u043a\u0442\u0438\u0432\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0439'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f'),
        ),
    ]
