# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-31 21:52
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20180131_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumainitem',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='content.MenuMainItem', verbose_name='\u0420\u043e\u0434\u0438\u0442\u0435\u043b\u044c'),
        ),
    ]
