# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20180131_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealersection',
            options={'verbose_name': '\u0411\u043b\u043e\u043a\u0438 \u0434\u0438\u043b\u0435\u0440\u0430\u043c'},
        ),
    ]
