# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 11:33
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20180201_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealersection',
            name='title',
            field=ckeditor.fields.RichTextField(default='\u0425\u043e\u0447\u0435\u0448\u044c \u0441\u0442\u0430\u0442\u044c \u0434\u0438\u043b\u0435\u0440\u043e\u043c CARAV?', verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0431\u043b\u043e\u043a\u0430 \u0434\u0438\u043b\u0435\u0440'),
        ),
    ]
