# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20180201_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingProductBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('button_text', models.CharField(max_length=32, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0432 \u043a\u043d\u043e\u043f\u043a\u0435')),
                ('image', models.ImageField(upload_to=b'', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430 \u043d\u0430 \u0437\u0430\u0434\u043d\u0435\u043c \u0444\u043e\u043d\u0435')),
                ('link', models.CharField(help_text='\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0439\u0442\u0435 \u0441\u0441\u044b\u043b\u043a\u0443 \u0432\u0438\u0434\u0430 /#html_id \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 \u043b\u044d\u043d\u0434\u0438\u043d\u0433\u0430. \u041e\u0441\u0442\u0430\u043b\u044c\u043d\u044b\u0435 \u0441\u0441\u044b\u043b\u043a\u0438 \u0443\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u043d\u043e\u0441\u0442\u044c\u044e (https://...)', max_length=255, verbose_name='URL-\u0430\u0434\u0440\u0435\u0441')),
            ],
            options={
                'verbose_name': '\u0411\u043b\u043e\u043a \u0433\u043b\u0430\u0432\u043d\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b',
                'verbose_name_plural': '\u0411\u043b\u043e\u043a\u0438 \u0433\u043b\u0430\u0432\u043d\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b',
            },
        ),
        migrations.AlterField(
            model_name='menuheaderitem',
            name='link',
            field=models.CharField(blank=True, help_text='\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0439\u0442\u0435 \u0441\u0441\u044b\u043b\u043a\u0443 \u0432\u0438\u0434\u0430 /#html_id \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 \u043b\u044d\u043d\u0434\u0438\u043d\u0433\u0430. \u041e\u0441\u0442\u0430\u043b\u044c\u043d\u044b\u0435 \u0441\u0441\u044b\u043b\u043a\u0438 \u0443\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u043d\u043e\u0441\u0442\u044c\u044e (https://...)', max_length=255, verbose_name='URL-\u0430\u0434\u0440\u0435\u0441'),
        ),
        migrations.AlterField(
            model_name='menumainitem',
            name='link',
            field=models.CharField(blank=True, help_text='\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0439\u0442\u0435 \u0441\u0441\u044b\u043b\u043a\u0443 \u0432\u0438\u0434\u0430 /#html_id \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 \u043b\u044d\u043d\u0434\u0438\u043d\u0433\u0430. \u041e\u0441\u0442\u0430\u043b\u044c\u043d\u044b\u0435 \u0441\u0441\u044b\u043b\u043a\u0438 \u0443\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u043d\u043e\u0441\u0442\u044c\u044e (https://...)', max_length=255, verbose_name='URL-\u0430\u0434\u0440\u0435\u0441'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='link',
            field=models.CharField(help_text='\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0439\u0442\u0435 \u0441\u0441\u044b\u043b\u043a\u0443 \u0432\u0438\u0434\u0430 /#html_id \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 \u043b\u044d\u043d\u0434\u0438\u043d\u0433\u0430. \u041e\u0441\u0442\u0430\u043b\u044c\u043d\u044b\u0435 \u0441\u0441\u044b\u043b\u043a\u0438 \u0443\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u043d\u043e\u0441\u0442\u044c\u044e (https://...)', max_length=255, verbose_name='URL-\u0430\u0434\u0440\u0435\u0441'),
        ),
    ]
