# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20180201_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='calendar_image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
