# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-03 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_auto_20180203_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingproductblock',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='landingproductblock',
            name='image_width',
        ),
    ]
