# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-05 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_auto_20180203_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField(verbose_name='\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u0430\u044f \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f',
                'verbose_name_plural': '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u0430\u044f \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='InformationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u041d\u043e\u043c\u0435\u0440/\u041f\u043e\u0447\u0442\u0430/\u0410\u0434\u0440\u0435\u0441/\u0420\u0430\u0441\u043f\u0438\u0441\u0430\u043d\u0438\u0435\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u0438\u043c\u0435\u043d\u043d\u043e \u0442\u0430\u043a\u0438\u0435 \u0438\u043c\u0435\u043d\u0430', max_length=64, verbose_name='\u0422\u0438\u043f \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u0438')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u0438',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u0438',
            },
        ),
        migrations.AddField(
            model_name='information',
            name='information_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information', to='content.InformationType', verbose_name='\u0422\u0438\u043f \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u0438'),
        ),
    ]
