# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-05 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_auto_20180205_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_title', models.CharField(max_length=128, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043d\u0430\u0434 \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u043e\u0439')),
                ('image', models.ImageField(upload_to='products', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430')),
                ('title', models.CharField(max_length=256, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u043e\u0434 \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u043e\u0439')),
                ('code', models.CharField(max_length=128, verbose_name='\u041a\u043e\u0434 \u0442\u043e\u0432\u0430\u0440\u0430')),
                ('available', models.BooleanField(default=False, verbose_name='\u041d\u0430\u043b\u0438\u0447\u0438\u0435 \u0442\u043e\u0432\u0430\u0440\u0430')),
                ('old_price', models.FloatField(blank=True, help_text='\u041d\u0435\u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e\u0435 \u043f\u043e\u043b\u0435', null=True, verbose_name='\u0421\u0442\u0430\u0440\u0430\u044f \u0446\u0435\u043d\u0430')),
                ('price', models.FloatField(verbose_name='\u0426\u0435\u043d\u0430 \u0432 \u0434\u043e\u043b\u043b\u0430\u0440\u0430\u0445')),
                ('ppc_price', models.FloatField(blank=True, help_text='\u041d\u0435\u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e\u0435 \u043f\u043e\u043b\u0435', null=True, verbose_name='\u0420\u0420\u0421 \u0446\u0435\u043d\u0430')),
                ('convert_price', models.FloatField(blank=True, help_text='\u041d\u0435\u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e\u0435 \u043f\u043e\u043b\u0435', null=True, verbose_name='\u0426\u0435\u043d\u0430 \u0432 \u0433\u0440\u0438\u0432\u043d\u0430\u0445')),
                ('discount', models.BooleanField(default=False, verbose_name='\u0410\u043a\u0446\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0422\u043e\u0432\u0430\u0440',
                'verbose_name_plural': '\u0422\u043e\u0432\u0430\u0440',
            },
        ),
    ]
