# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-05 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='credit',
            field=models.FloatField(blank=True, help_text='\u041d\u0435\u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e\u0435 \u043f\u043e\u043b\u0435', null=True, verbose_name='\u041a\u0440\u0435\u0434\u0438\u0442 \u0432 %'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='blog_images', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430'),
        ),
    ]
