# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-05 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_auto_20180205_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043f\u043e\u0434 \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u043e\u0439'),
        ),
        migrations.AlterField(
            model_name='product',
            name='top_title',
            field=models.TextField(verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u043d\u0430\u0434 \u043a\u0430\u0440\u0442\u0438\u043d\u043a\u043e\u0439'),
        ),
    ]
