# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-05 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_auto_20180205_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField(verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430 \u0432 %')),
            ],
            options={
                'verbose_name': '\u0410\u043a\u0446\u0438\u043e\u043d\u043d\u044b\u0439 \u0442\u043e\u0432\u0430\u0440',
                'verbose_name_plural': '\u0410\u043a\u0446\u0438\u043e\u043d\u043d\u044b\u0435 \u0442\u043e\u0432\u0430\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='PopularProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u043f\u0443\u043b\u044f\u0440\u043d\u044b\u0439 \u0442\u043e\u0432\u0430\u0440',
                'verbose_name_plural': '\u041f\u043e\u043f\u0443\u043b\u044f\u0440\u043d\u044b\u0435 \u0442\u043e\u0432\u0430\u0440\u044b',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='convert_price',
            field=models.FloatField(help_text='\u041d\u0435\u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e\u0435 \u043f\u043e\u043b\u0435', null=True, verbose_name='\u0426\u0435\u043d\u0430 \u0432 \u0433\u0440\u0438\u0432\u043d\u0430\u0445'),
        ),
        migrations.AddField(
            model_name='popularproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440'),
        ),
        migrations.AddField(
            model_name='discountproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440'),
        ),
    ]
