# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-05 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_auto_20180205_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='convert_price',
            field=models.FloatField(default=0, help_text='\u041d\u0435\u043e\u0431\u044f\u0437\u0430\u0442\u0435\u043b\u044c\u043d\u043e\u0435 \u043f\u043e\u043b\u0435', verbose_name='\u0426\u0435\u043d\u0430 \u0432 \u0433\u0440\u0438\u0432\u043d\u0430\u0445'),
            preserve_default=False,
        ),
    ]
