# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-05 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_auto_20180205_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='content.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440'),
        ),
        migrations.AlterField(
            model_name='popularproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='popular', to='content.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440'),
        ),
    ]
