# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-05 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_auto_20180205_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingproductblock',
            name='name',
        ),
        migrations.AddField(
            model_name='landingproductblock',
            name='category',
            field=models.OneToOneField(help_text="\u0412\u044b\u0431\u0438\u0440\u0430\u0439\u0442\u0435 \u0441\u0430\u043c\u044b\u0435 '\u0441\u0442\u0430\u0440\u0448\u0438\u0435' \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438, \u0443 \u043a\u043e\u0442\u043e\u0440\u044b\u0445 \u043d\u0435\u0442\u0443 '\u0440\u043e\u0434\u0438\u0442\u0435\u043b\u0435\u0439'", null=True, on_delete=django.db.models.deletion.CASCADE, to='content.MenuMainItem', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
    ]
