# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-05 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_auto_20180205_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingproductblock',
            name='name',
            field=models.CharField(default=123, max_length=64, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
            preserve_default=False,
        ),
    ]
