# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-05 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_landingproductblock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingproductblock',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
