# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-05 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_auto_20180205_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingproductblock',
            name='name',
        ),
    ]
