# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-05 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_auto_20180205_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealersection',
            name='link',
        ),
        migrations.RemoveField(
            model_name='menuheaderitem',
            name='link',
        ),
        migrations.RemoveField(
            model_name='menumainitem',
            name='link',
        ),
    ]
