# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-06 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_auto_20180205_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=64, verbose_name='\u0421\u043e\u0434\u0435\u0440\u0436\u0438\u043c\u043e\u0435')),
            ],
            options={
                'verbose_name': '\u0411\u0430\u043d\u043d\u0435\u0440',
                'verbose_name_plural': '\u0411\u0430\u043d\u043d\u0435\u0440\u044b \u043c\u0435\u0436\u0434\u0443 \u0442\u043e\u0432\u0430\u0440\u0430\u043c\u0438 \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435 \u043a\u0430\u0442\u0430\u043b\u043e\u0433\u0430',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_photos', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430')),
            ],
            options={
                'verbose_name': '\u0424\u043e\u0442\u043e \u0442\u043e\u0432\u0430\u0440\u0430',
                'verbose_name_plural': '\u0424\u043e\u0442\u043e \u0442\u043e\u0432\u0430\u0440\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='Rait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='\u0420\u0435\u0439\u0442\u0438\u043d\u0433')),
            ],
            options={
                'verbose_name': '\u0420\u0435\u0439\u0442\u0438\u043d\u0433',
                'verbose_name_plural': '\u0420\u0435\u0439\u0442\u0438\u043d\u0433\u0438',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='top_title',
        ),
        migrations.AddField(
            model_name='product',
            name='car',
            field=models.ManyToManyField(to='content.MenuMainItem', verbose_name='\u0421\u043e\u0432\u043c\u0435\u0441\u0442\u0438\u043c\u043e\u0441\u0442\u044c \u0441 \u043c\u0430\u0448\u0438\u043d\u0430\u043c\u0438'),
        ),
        migrations.AddField(
            model_name='product',
            name='information',
            field=models.TextField(default='', help_text='\u041e\u0441\u043e\u0431\u0435\u043d\u043d\u043e\u0441\u0442\u0438, \u0442\u0438\u043f...', verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u0442\u043e\u0432\u0430\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.TextField(default='', verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='product',
            name='convert_price',
            field=models.FloatField(help_text='\u041e\u043f\u0442\u043e\u0432\u0430\u044f \u0446\u0435\u043d\u0430', verbose_name='\u0426\u0435\u043d\u0430 \u0432 \u0433\u0440\u0438\u0432\u043d\u0430\u0445'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ppc_price',
            field=models.FloatField(default=0, help_text='\u0420\u043e\u0437\u043d\u0438\u0447\u043d\u0430\u044f \u0446\u0435\u043d\u0430', verbose_name='\u0420\u0420\u0421 \u0446\u0435\u043d\u0430'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440'),
        ),
        migrations.AddField(
            model_name='product',
            name='rait',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='content.Rait', verbose_name='\u0420\u0435\u0439\u0442\u0438\u043d\u0433 \u0442\u043e\u0432\u0430\u0440\u0430'),
        ),
    ]
