# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-06 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0042_auto_20180206_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='convert_price',
        ),
        migrations.AddField(
            model_name='product',
            name='course',
            field=models.FloatField(default=25, verbose_name='\u041a\u0443\u0440\u0441 \u0434\u043e\u043b\u043b\u0430\u0440\u0430 \u043a \u0433\u0440\u0438\u0432\u043d\u0435'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ppc_price',
            field=models.FloatField(default=0, help_text='\u0420\u043e\u0437\u043d\u0438\u0447\u043d\u0430\u044f \u0446\u0435\u043d\u0430', verbose_name='\u0420\u0420\u0421 \u0446\u0435\u043d\u0430 (\u0434\u043e\u043b\u043b\u0430\u0440)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='\u0426\u0435\u043d\u0430 \u0434\u043b\u044f \u043e\u043f\u0442\u043e\u0432\u0438\u043a\u043e\u0432 (\u0434\u043e\u043b\u043b\u0430\u0440)'),
        ),
    ]
