# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-07 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0044_auto_20180206_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.BooleanField(default=False, help_text='\u0415\u0441\u043b\u0438 \u0432\u043a\u043b\u044e\u0447\u0438\u0442\u044c, \u0442\u043e \u0433\u0440\u0438\u0432\u043d\u044b\u0415\u0441\u043b\u0438 \u043e\u0442\u043a\u043b\u044e\u0447\u0438\u0442\u044c, \u0442\u043e \u0434\u043e\u043b\u043b\u0430\u0440\u044b', verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430, \u0432 \u043a\u043e\u0442\u043e\u0440\u043e\u0439 \u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c \u0446\u0435\u043d\u0443'),
        ),
    ]
