# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-07 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0047_auto_20180207_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('link', models.CharField(help_text='\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0439\u0442\u0435 \u0441\u0441\u044b\u043b\u043a\u0443 \u0432\u0438\u0434\u0430 /#html_id \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 \u043b\u044d\u043d\u0434\u0438\u043d\u0433\u0430. \u041e\u0441\u0442\u0430\u043b\u044c\u043d\u044b\u0435 \u0441\u0441\u044b\u043b\u043a\u0438 \u0443\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u043d\u043e\u0441\u0442\u044c\u044e (https://...)', max_length=255, verbose_name='URL-\u0430\u0434\u0440\u0435\u0441')),
                ('information', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u041c\u043e\u0434\u0435\u043b\u044c \u0430\u0432\u0442\u043e\u043c\u043e\u0431\u0438\u043b\u044f',
                'verbose_name_plural': '\u041c\u043e\u0434\u0435\u043b\u0438 \u0430\u0432\u0442\u043e\u043c\u043e\u0431\u0438\u043b\u0435\u0439',
            },
        ),
        migrations.CreateModel(
            name='StampCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('image', models.ImageField(upload_to='car_icons', verbose_name='\u0418\u043a\u043e\u043d\u043a\u0430')),
                ('link', models.CharField(help_text='\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0439\u0442\u0435 \u0441\u0441\u044b\u043b\u043a\u0443 \u0432\u0438\u0434\u0430 /#html_id \u0434\u043b\u044f \u0431\u043b\u043e\u043a\u0430 \u043b\u044d\u043d\u0434\u0438\u043d\u0433\u0430. \u041e\u0441\u0442\u0430\u043b\u044c\u043d\u044b\u0435 \u0441\u0441\u044b\u043b\u043a\u0438 \u0443\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u043d\u043e\u0441\u0442\u044c\u044e (https://...)', max_length=255, verbose_name='URL-\u0430\u0434\u0440\u0435\u0441')),
                ('information', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u041c\u0430\u0440\u043a\u0430 \u0430\u0432\u0442\u043e\u043c\u043e\u0431\u0438\u043b\u044f',
                'verbose_name_plural': '\u041c\u0430\u0440\u043a\u0438 \u0430\u0432\u0442\u043e\u043c\u043e\u0431\u0438\u043b\u044f',
            },
        ),
        migrations.CreateModel(
            name='YearCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='\u0413\u043e\u0434 \u0432\u044b\u043f\u0443\u0441\u043a\u0430')),
            ],
            options={
                'verbose_name': '\u0413\u043e\u0434 \u0432\u044b\u043f\u0443\u0441\u043a\u0430 \u043c\u0430\u0448\u0438\u043d\u044b',
                'verbose_name_plural': '\u0413\u043e\u0434\u0430 \u0432\u044b\u043f\u0443\u0441\u043a\u0430 \u043c\u0430\u0448\u0438\u043d',
            },
        ),
        migrations.AddField(
            model_name='modelcar',
            name='stamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='content.StampCar', verbose_name='\u041c\u0430\u0440\u043a\u0430 \u0430\u0432\u0442\u043e\u043c\u043e\u0431\u0438\u043b\u044f'),
        ),
        migrations.AddField(
            model_name='modelcar',
            name='years',
            field=models.ManyToManyField(to='content.YearCar', verbose_name='\u0413\u043e\u0434\u0430 \u0432\u044b\u043f\u0443\u0441\u043a\u0430'),
        ),
    ]
