# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-07 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0048_auto_20180207_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stampcar',
            options={'verbose_name': '\u041c\u0430\u0440\u043a\u0430 \u0430\u0432\u0442\u043e\u043c\u043e\u0431\u0438\u043b\u044f', 'verbose_name_plural': '\u041c\u0430\u0440\u043a\u0438 \u0430\u0432\u0442\u043e\u043c\u043e\u0431\u0438\u043b\u0435\u0439'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='car',
        ),
        migrations.AddField(
            model_name='product',
            name='car_compatibility',
            field=models.ManyToManyField(to='content.ModelCar', verbose_name='\u0421\u043e\u0432\u043c\u0435\u0441\u0442\u0438\u043c\u043e\u0441\u0442\u044c \u0441 \u043c\u0430\u0448\u0438\u043d\u0430\u043c\u0438'),
        ),
    ]
