# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-07 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0049_auto_20180207_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u0440\u0437\u0438\u043d\u0430',
                'verbose_name_plural': '\u041a\u043e\u0440\u0437\u0438\u043d\u044b',
            },
        ),
        migrations.CreateModel(
            name='BasketProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Basket', verbose_name='\u041a\u043e\u0440\u0437\u0438\u043d\u0430')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u043e\u043c\u0435\u0436\u0443\u0442\u043e\u0447\u043d\u0430\u044f \u0442\u0430\u0431\u043b\u0438\u0446\u0430 \u041a\u043e\u0440\u0437\u0438\u043d\u0430-\u0422\u043e\u0432\u0430\u0440',
                'verbose_name_plural': '\u041f\u0440\u043e\u043c\u0435\u0436\u0443\u0442\u043e\u0447\u043d\u044b\u0435 \u0442\u0430\u0431\u043b\u0438\u0446\u044b \u041a\u043e\u0440\u0437\u0438\u043d\u0430-\u0422\u043e\u0432\u0430\u0440',
            },
        ),
        migrations.CreateModel(
            name='DeliveryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='\u0418\u043c\u044f')),
                ('last_name', models.CharField(max_length=64, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('city', models.CharField(max_length=128, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('phone_number', models.CharField(max_length=32, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430')),
                ('is_sms', models.BooleanField(default=False, verbose_name='\u041e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u044c \u0421\u041c\u0421 \u0441 \u043d\u043e\u043c\u0435\u0440\u043e\u043c \u0422\u041d\u041d')),
                ('nova_poshta_stock', models.CharField(max_length=64, verbose_name='\u0421\u043a\u043b\u0430\u0434 "\u041d\u043e\u0432\u043e\u0439 \u041f\u043e\u0447\u0442\u044b"')),
                ('cod_sum', models.FloatField(verbose_name='\u0421\u0443\u043c\u043c\u0430 \u043d\u0430\u043b\u043e\u0436\u0435\u043d\u043d\u043e\u0433\u043e \u043f\u043b\u0430\u0442\u0435\u0436\u0430')),
                ('is_cod', models.BooleanField(default=False, verbose_name='\u041e\u0442\u043f\u0440\u0430\u0432\u043a\u0430 \u0431\u0435\u0437 \u0434\u0435\u043d\u0435\u0433')),
                ('email', models.EmailField(max_length=254, verbose_name='\u042d\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u0430\u044f \u043f\u043e\u0447\u0442\u0430')),
                ('commentary', models.TextField(verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
            ],
            options={
                'verbose_name': '\u0414\u0430\u043d\u043d\u044b\u0435 \u043e \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0435',
                'verbose_name_plural': '\u0414\u0430\u043d\u043d\u044b\u0435 \u043e \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0430\u0445',
            },
        ),
        migrations.AddField(
            model_name='basket',
            name='products',
            field=models.ManyToManyField(through='content.BasketProduct', to='content.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440'),
        ),
    ]
