# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-07 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0050_auto_20180207_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydata',
            name='cod_sum',
            field=models.FloatField(blank=True, null=True, verbose_name='\u0421\u0443\u043c\u043c\u0430 \u043d\u0430\u043b\u043e\u0436\u0435\u043d\u043d\u043e\u0433\u043e \u043f\u043b\u0430\u0442\u0435\u0436\u0430'),
        ),
        migrations.AlterField(
            model_name='deliverydata',
            name='commentary',
            field=models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439'),
        ),
    ]
