# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-09 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0053_auto_20180207_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='products',
        ),
        migrations.RemoveField(
            model_name='basketproduct',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='basketproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='BasketProduct',
        ),
    ]
