# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-09 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0054_auto_20180209_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u043e\u043c\u0435\u0436\u0443\u0442\u043e\u0447\u043d\u0430\u044f \u0442\u0430\u0431\u043b\u0438\u0446\u0430 \u041a\u043e\u0440\u0437\u0438\u043d\u0430-\u0422\u043e\u0432\u0430\u0440',
                'verbose_name_plural': '\u041f\u0440\u043e\u043c\u0435\u0436\u0443\u0442\u043e\u0447\u043d\u044b\u0435 \u0442\u0430\u0431\u043b\u0438\u0446\u044b \u041a\u043e\u0440\u0437\u0438\u043d\u0430-\u0422\u043e\u0432\u0430\u0440',
            },
        ),
        migrations.CreateModel(
            name='ChipBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(through='content.BasketProduct', to='content.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u043a\u0443\u043f\u043e\u0447\u043d\u0430\u044f \u043a\u043e\u0440\u0437\u0438\u043d\u0430',
                'verbose_name_plural': '\u041f\u043e\u043a\u0443\u043f\u043e\u0447\u043d\u044b\u0435 \u043a\u043e\u0440\u0437\u0438\u043d\u044b',
            },
        ),
        migrations.AddField(
            model_name='basketproduct',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.ChipBasket', verbose_name='\u041a\u043e\u0440\u0437\u0438\u043d\u0430'),
        ),
        migrations.AddField(
            model_name='basketproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Product', verbose_name='\u0422\u043e\u0432\u0430\u0440'),
        ),
    ]
