# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-13 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0057_chipbasket_delivery_way'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountproduct',
            name='discount',
            field=models.FloatField(verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430'),
        ),
    ]
