# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-13 13:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0058_auto_20180213_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('\u041e\u0444\u043e\u0440\u043c\u043b\u0435\u043d', '\u041e\u0444\u043e\u0440\u043c\u043b\u0435\u043d'), ('\u0412 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0435', '\u0412 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0435'), ('\u041e\u043f\u043b\u0430\u0447\u0435\u043d', '\u041e\u043f\u043b\u0430\u0447\u0435\u043d'), ('\u0417\u0430\u043a\u043e\u043d\u0447\u0435\u043d', '\u0417\u0430\u043a\u043e\u043d\u0447\u0435\u043d')], max_length=128, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u0437\u0430\u043a\u0430\u0437\u0430')),
                ('cod', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u0422\u041d\u041d')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u043a\u0430\u0437',
                'verbose_name_plural': '\u0417\u0430\u043a\u0430\u0437\u044b',
            },
        ),
        migrations.RemoveField(
            model_name='chipbasket',
            name='delivery_way',
        ),
        migrations.AddField(
            model_name='chipbasket',
            name='is_framed',
            field=models.BooleanField(default=False, verbose_name='\u0421\u0432\u044f\u0437\u0430\u043d\u0430 \u0441 \u0437\u0430\u043a\u0430\u0437\u043e\u043c'),
        ),
        migrations.AddField(
            model_name='order',
            name='basket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content.ChipBasket', verbose_name='\u041a\u043e\u0440\u0437\u0438\u043d\u0430'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content.DeliveryData', verbose_name='\u0414\u0430\u043d\u043d\u044b\u0435 \u043e \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0435'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_way',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='content.Delivery', verbose_name='\u0421\u043f\u043e\u0441\u043e\u0431 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0417\u0430\u0440\u0435\u0433\u0435\u0441\u0442\u0440\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0439 \u043a\u043b\u0438\u0435\u043d\u0442'),
        ),
    ]
