# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-13 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0060_auto_20180213_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryWay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0421\u043f\u043e\u0441\u043e\u0431 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438',
                'verbose_name_plural': '\u0421\u043f\u043e\u0441\u043e\u0431\u044b \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438',
            },
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_way',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Delivery', verbose_name='\u0414\u043e\u0441\u0442\u0430\u0432\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_way',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.DeliveryWay', verbose_name='\u0421\u043f\u043e\u0441\u043e\u0431 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438'),
        ),
    ]
