# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-14 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0063_auto_20180213_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='basket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='content.ChipBasket', verbose_name='\u041a\u043e\u0440\u0437\u0438\u043d\u0430'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('\u041e\u0444\u043e\u0440\u043c\u043b\u0435\u043d', '\u041e\u0444\u043e\u0440\u043c\u043b\u0435\u043d'), ('\u0412 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0435', '\u0412 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u043a\u0435'), ('\u041e\u043f\u043b\u0430\u0447\u0435\u043d', '\u041e\u043f\u043b\u0430\u0447\u0435\u043d'), ('\u0417\u0430\u043a\u043e\u043d\u0447\u0435\u043d', '\u0417\u0430\u043a\u043e\u043d\u0447\u0435\u043d')], default='\u0421\u043e\u0437\u0434\u0430\u043d', max_length=128, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u0437\u0430\u043a\u0430\u0437\u0430'),
        ),
    ]
