# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-14 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0065_personalaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
