# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-20 14:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0069_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='\u041a\u0443\u0440\u0441 \u0434\u043e\u043b\u043b\u0430\u0440\u0430 \u043a \u0433\u0440\u0438\u0432\u043d\u0435')),
            ],
            options={
                'verbose_name': '\u041a\u0443\u0440\u0441 \u0434\u043e\u043b\u043b\u0430\u0440\u0430 \u043a \u0433\u0440\u0438\u0432\u043d\u0435',
                'verbose_name_plural': '\u041a\u0443\u0440\u0441 \u0434\u043e\u043b\u043b\u0430\u0440\u0430 \u043a \u0433\u0440\u0438\u0432\u043d\u0435',
            },
        ),
    ]
