# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-20 14:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0070_exchangerate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerate',
            name='rate',
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='rate_buy',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='\u041a\u0443\u0440\u0441 \u0434\u043e\u043b\u043b\u0430\u0440\u0430 \u043a \u0433\u0440\u0438\u0432\u043d\u0435, \u043f\u0440\u043e\u0434\u0430\u0436\u0430'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='rate_sale',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='\u041a\u0443\u0440\u0441 \u0434\u043e\u043b\u043b\u0430\u0440\u0430 \u043a \u0433\u0440\u0438\u0432\u043d\u0435, \u043f\u043e\u043a\u0443\u043f\u043a\u0430'),
        ),
    ]
