# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-20 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0071_auto_20180220_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingproductblock',
            name='button_text',
            field=models.CharField(default='\u041f\u043e\u0434\u0440\u043e\u0431\u043d\u0435\u0435', max_length=32, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0432 \u043a\u043d\u043e\u043f\u043a\u0435'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rait',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='content.Rait', verbose_name='\u0420\u0435\u0439\u0442\u0438\u043d\u0433 \u0442\u043e\u0432\u0430\u0440\u0430'),
        ),
    ]
