# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-21 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0073_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rait',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Rait', verbose_name='\u0420\u0435\u0439\u0442\u0438\u043d\u0433'),
        ),
    ]
